server:
  port: ${PORT:8080}

spring:
  application:
    name: hello-world-backend

# CORS configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  allow-credentials: true

# Logging configuration
logging:
  level:
    root: INFO
    com.example.helloworld: DEBUG